<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseSharedCompilation>false</UseSharedCompilation>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="7.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="OpenAI" Version="2.1.0" />
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="8.21.180" />
    <PackageReference Include="System.DirectoryServices" Version="8.0.0" />
  </ItemGroup>

  <Target Name="KillRunningHost" BeforeTargets="Build">
    <Exec Command="taskkill /IM EOM.Web.exe /F 2&gt;nul" IgnoreExitCode="true" />
  </Target>

</Project>
