// <auto-generated />
using System;
using EOM.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EOM.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250714053442_MarkAsApplied")]
    partial class MarkAsApplied
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EOM.Web.Models.AwardCycle", b =>
                {
                    b.Property<int>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValueSql("SEQ_AWARDCYCLE.NEXTVAL");

                    b.Property<int>("AwardTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Month")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("NominationEnd")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("NominationStart")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Year")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("CycleId");

                    b.HasIndex("AwardTypeId")
                        .HasDatabaseName("IX_AwardCycle_AwardType");

                    b.ToTable("AwardCycles");
                });

            modelBuilder.Entity("EOM.Web.Models.AwardType", b =>
                {
                    b.Property<int>("AwardTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValueSql("SEQ_AWARDTYPE.NEXTVAL");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("AwardTypeId");

                    b.ToTable("AwardTypes");
                });

            modelBuilder.Entity("EOM.Web.Models.CommitteeMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValueSql("SEQ_COMMITTEE.NEXTVAL");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_Committee_Employee");

                    b.ToTable("CommitteeMembers");
                });

            modelBuilder.Entity("EOM.Web.Models.Criterion", b =>
                {
                    b.Property<int>("CriterionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValueSql("SEQ_CRITERION.NEXTVAL");

                    b.Property<int>("AwardTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<decimal>("WeightPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)");

                    b.HasKey("CriterionId");

                    b.HasIndex("AwardTypeId")
                        .HasDatabaseName("IX_Criterion_AwardType");

                    b.ToTable("Criteria");
                });

            modelBuilder.Entity("EOM.Web.Models.DepartmentQuota", b =>
                {
                    b.Property<long>("DepartmentId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("AwardTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("MaxNominations")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("DepartmentId", "AwardTypeId");

                    b.HasIndex("AwardTypeId")
                        .HasDatabaseName("IX_DeptQuota_AwardType");

                    b.ToTable("DepartmentQuotas");
                });

            modelBuilder.Entity("EOM.Web.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EMPLOYEEID");

                    b.Property<string>("ActiveDirectoryId")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ACTIVEDIRECTORYID");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DEPARTMENTID");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FIRSTNAME");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("HIREDATE");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ISACTIVE");

                    b.Property<int>("IsManager")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IS_MANAGER");

                    b.Property<string>("JobTitle")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("JOBTITLE");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("LASTNAME");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MANAGERID");

                    b.Property<string>("ManagerName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MANAGERNAME");

                    b.Property<string>("Password")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PHONENUMBER");

                    b.HasKey("EmployeeId");

                    b.ToTable((string)null);

                    b.ToView("VW_EOM_EMPLOYEES", (string)null);
                });

            modelBuilder.Entity("EOM.Web.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValueSql("SEQ_EVALUATION.NEXTVAL");

                    b.Property<int>("CommitteeMemberId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("NominationId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("EvaluationId");

                    b.HasIndex("CommitteeMemberId")
                        .HasDatabaseName("IX_Evaluation_Committee");

                    b.HasIndex("NominationId")
                        .HasDatabaseName("IX_Evaluation_Nomination");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("EOM.Web.Models.EvaluationScore", b =>
                {
                    b.Property<int>("EvaluationId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SubCriteriaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("EvaluationScoreId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Note")
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int?>("Score")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("EvaluationId", "SubCriteriaId");

                    b.HasIndex("EvaluationId")
                        .HasDatabaseName("IX_EvalScore_Evaluation");

                    b.HasIndex("SubCriteriaId")
                        .HasDatabaseName("IX_EvalScore_SubCriteria");

                    b.ToTable("EvaluationScores");
                });

            modelBuilder.Entity("EOM.Web.Models.ManagerScore", b =>
                {
                    b.Property<int>("NominationId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SubCriteriaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int?>("Score")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("NominationId", "SubCriteriaId");

                    b.HasIndex("NominationId")
                        .HasDatabaseName("IX_MgrScore_Nomination");

                    b.HasIndex("SubCriteriaId")
                        .HasDatabaseName("IX_MgrScore_SubCriteria");

                    b.ToTable("ManagerScores");
                });

            modelBuilder.Entity("EOM.Web.Models.Nomination", b =>
                {
                    b.Property<int>("NominationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValueSql("SEQ_NOMINATION.NEXTVAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("CycleId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("SelectedByCommitteeMemberId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("SupportingDocPath")
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<DateTime?>("WonAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("NominationId");

                    b.HasIndex("CycleId")
                        .HasDatabaseName("IX_Nomination_Cycle");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_Nomination_Employee");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("IX_Nomination_Manager");

                    b.HasIndex("SelectedByCommitteeMemberId")
                        .HasDatabaseName("IX_Nomination_SelCommittee");

                    b.ToTable("Nominations");
                });

            modelBuilder.Entity("EOM.Web.Models.SubCriteria", b =>
                {
                    b.Property<int>("SubCriteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValueSql("SEQ_SUBCRITERIA.NEXTVAL");

                    b.Property<int>("CriterionId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("GradingScale")
                        .HasMaxLength(1000)
                        .HasColumnType("NCLOB");

                    b.Property<byte>("MaxScore")
                        .HasColumnType("NUMBER(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("SubCriteriaCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.HasKey("SubCriteriaId");

                    b.HasIndex("CriterionId")
                        .HasDatabaseName("IX_SubCriteria_Criterion");

                    b.ToTable("SubCriteria");
                });

            modelBuilder.Entity("EOM.Web.Models.AwardCycle", b =>
                {
                    b.HasOne("EOM.Web.Models.AwardType", "AwardType")
                        .WithMany("AwardCycles")
                        .HasForeignKey("AwardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AwardCycle_AwardType");

                    b.Navigation("AwardType");
                });

            modelBuilder.Entity("EOM.Web.Models.CommitteeMember", b =>
                {
                    b.HasOne("EOM.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Committee_Employee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EOM.Web.Models.Criterion", b =>
                {
                    b.HasOne("EOM.Web.Models.AwardType", "AwardType")
                        .WithMany("Criteria")
                        .HasForeignKey("AwardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Criterion_AwardType");

                    b.Navigation("AwardType");
                });

            modelBuilder.Entity("EOM.Web.Models.DepartmentQuota", b =>
                {
                    b.HasOne("EOM.Web.Models.AwardType", "AwardType")
                        .WithMany("DepartmentQuotas")
                        .HasForeignKey("AwardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DeptQuota_AwardType");

                    b.Navigation("AwardType");
                });

            modelBuilder.Entity("EOM.Web.Models.Evaluation", b =>
                {
                    b.HasOne("EOM.Web.Models.CommitteeMember", "CommitteeMember")
                        .WithMany("Evaluations")
                        .HasForeignKey("CommitteeMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Evaluation_Committee");

                    b.HasOne("EOM.Web.Models.Nomination", "Nomination")
                        .WithMany("Evaluations")
                        .HasForeignKey("NominationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Evaluation_Nomination");

                    b.Navigation("CommitteeMember");

                    b.Navigation("Nomination");
                });

            modelBuilder.Entity("EOM.Web.Models.EvaluationScore", b =>
                {
                    b.HasOne("EOM.Web.Models.Evaluation", "Evaluation")
                        .WithMany("EvaluationScores")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EvalScore_Evaluation");

                    b.HasOne("EOM.Web.Models.SubCriteria", "SubCriteria")
                        .WithMany("EvaluationScores")
                        .HasForeignKey("SubCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EvalScore_SubCriteria");

                    b.Navigation("Evaluation");

                    b.Navigation("SubCriteria");
                });

            modelBuilder.Entity("EOM.Web.Models.ManagerScore", b =>
                {
                    b.HasOne("EOM.Web.Models.Nomination", "Nomination")
                        .WithMany("ManagerScores")
                        .HasForeignKey("NominationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MgrScore_Nomination");

                    b.HasOne("EOM.Web.Models.SubCriteria", "SubCriteria")
                        .WithMany("ManagerScores")
                        .HasForeignKey("SubCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MgrScore_SubCriteria");

                    b.Navigation("Nomination");

                    b.Navigation("SubCriteria");
                });

            modelBuilder.Entity("EOM.Web.Models.Nomination", b =>
                {
                    b.HasOne("EOM.Web.Models.AwardCycle", "AwardCycle")
                        .WithMany("Nominations")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Nomination_AwardCycle");

                    b.HasOne("EOM.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Nomination_Employee");

                    b.HasOne("EOM.Web.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Nomination_Manager");

                    b.HasOne("EOM.Web.Models.Employee", "SelectedByCommitteeMember")
                        .WithMany()
                        .HasForeignKey("SelectedByCommitteeMemberId")
                        .HasConstraintName("FK_Nomination_Committee");

                    b.Navigation("AwardCycle");

                    b.Navigation("Employee");

                    b.Navigation("Manager");

                    b.Navigation("SelectedByCommitteeMember");
                });

            modelBuilder.Entity("EOM.Web.Models.SubCriteria", b =>
                {
                    b.HasOne("EOM.Web.Models.Criterion", "Criterion")
                        .WithMany("SubCriteria")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SubCriteria_Criterion");

                    b.Navigation("Criterion");
                });

            modelBuilder.Entity("EOM.Web.Models.AwardCycle", b =>
                {
                    b.Navigation("Nominations");
                });

            modelBuilder.Entity("EOM.Web.Models.AwardType", b =>
                {
                    b.Navigation("AwardCycles");

                    b.Navigation("Criteria");

                    b.Navigation("DepartmentQuotas");
                });

            modelBuilder.Entity("EOM.Web.Models.CommitteeMember", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("EOM.Web.Models.Criterion", b =>
                {
                    b.Navigation("SubCriteria");
                });

            modelBuilder.Entity("EOM.Web.Models.Evaluation", b =>
                {
                    b.Navigation("EvaluationScores");
                });

            modelBuilder.Entity("EOM.Web.Models.Nomination", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("ManagerScores");
                });

            modelBuilder.Entity("EOM.Web.Models.SubCriteria", b =>
                {
                    b.Navigation("EvaluationScores");

                    b.Navigation("ManagerScores");
                });
#pragma warning restore 612, 618
        }
    }
}
