// <auto-generated />
using System;
using EOM.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EOM.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250708191413_ClearNominationsOnly")]
    partial class ClearNominationsOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EOM.Web.Models.AwardCycle", b =>
                {
                    b.Property<int>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CycleId"));

                    b.Property<int>("AwardTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime>("NominationEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NominationStart")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CycleId");

                    b.HasIndex("AwardTypeId");

                    b.ToTable("AwardCycles");
                });

            modelBuilder.Entity("EOM.Web.Models.AwardType", b =>
                {
                    b.Property<int>("AwardTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AwardTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AwardTypeId");

                    b.ToTable("AwardTypes");
                });

            modelBuilder.Entity("EOM.Web.Models.CommitteeMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("CommitteeMembers");
                });

            modelBuilder.Entity("EOM.Web.Models.Criterion", b =>
                {
                    b.Property<int>("CriterionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CriterionId"));

                    b.Property<int>("AwardTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("WeightPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("CriterionId");

                    b.HasIndex("AwardTypeId");

                    b.ToTable("Criteria");
                });

            modelBuilder.Entity("EOM.Web.Models.DepartmentQuota", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("AwardTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MaxNominations")
                        .HasColumnType("int");

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId", "AwardTypeId");

                    b.HasIndex("AwardTypeId");

                    b.ToTable("DepartmentQuotas");
                });

            modelBuilder.Entity("EOM.Web.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("ActiveDirectoryId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EOM.Web.Models.EmployeeManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ManagerId");

                    b.ToTable("EmployeeManagers");
                });

            modelBuilder.Entity("EOM.Web.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EvaluationId"));

                    b.Property<int>("CommitteeMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NominationId")
                        .HasColumnType("int");

                    b.HasKey("EvaluationId");

                    b.HasIndex("CommitteeMemberId");

                    b.HasIndex("NominationId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("EOM.Web.Models.EvaluationScore", b =>
                {
                    b.Property<int>("EvaluationId")
                        .HasColumnType("int");

                    b.Property<int>("SubCriteriaId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<byte>("Score")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("EvaluationId", "SubCriteriaId");

                    b.HasIndex("SubCriteriaId");

                    b.ToTable("EvaluationScores");
                });

            modelBuilder.Entity("EOM.Web.Models.ManagerScore", b =>
                {
                    b.Property<int>("NominationId")
                        .HasColumnType("int");

                    b.Property<int>("SubCriteriaId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.HasKey("NominationId", "SubCriteriaId");

                    b.HasIndex("SubCriteriaId");

                    b.ToTable("ManagerScores");
                });

            modelBuilder.Entity("EOM.Web.Models.Nomination", b =>
                {
                    b.Property<int>("NominationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NominationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("SupportingDocPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("NominationId");

                    b.HasIndex("CycleId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Nominations");
                });

            modelBuilder.Entity("EOM.Web.Models.SubCriteria", b =>
                {
                    b.Property<int>("SubCriteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SubCriteriaId"));

                    b.Property<int>("CriterionId")
                        .HasColumnType("int");

                    b.Property<string>("GradingScale")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<byte>("MaxScore")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SubCriteriaCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("SubCriteriaId");

                    b.HasIndex("CriterionId");

                    b.ToTable("SubCriteria");
                });

            modelBuilder.Entity("EOM.Web.Models.AwardCycle", b =>
                {
                    b.HasOne("EOM.Web.Models.AwardType", "AwardType")
                        .WithMany("AwardCycles")
                        .HasForeignKey("AwardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwardType");
                });

            modelBuilder.Entity("EOM.Web.Models.CommitteeMember", b =>
                {
                    b.HasOne("EOM.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EOM.Web.Models.Criterion", b =>
                {
                    b.HasOne("EOM.Web.Models.AwardType", "AwardType")
                        .WithMany("Criteria")
                        .HasForeignKey("AwardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwardType");
                });

            modelBuilder.Entity("EOM.Web.Models.DepartmentQuota", b =>
                {
                    b.HasOne("EOM.Web.Models.AwardType", "AwardType")
                        .WithMany("DepartmentQuotas")
                        .HasForeignKey("AwardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwardType");
                });

            modelBuilder.Entity("EOM.Web.Models.EmployeeManager", b =>
                {
                    b.HasOne("EOM.Web.Models.Employee", "Employee")
                        .WithMany("Managers")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EOM.Web.Models.Employee", "Manager")
                        .WithMany("ManagedEmployees")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("EOM.Web.Models.Evaluation", b =>
                {
                    b.HasOne("EOM.Web.Models.CommitteeMember", "CommitteeMember")
                        .WithMany("Evaluations")
                        .HasForeignKey("CommitteeMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EOM.Web.Models.Nomination", "Nomination")
                        .WithMany("Evaluations")
                        .HasForeignKey("NominationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommitteeMember");

                    b.Navigation("Nomination");
                });

            modelBuilder.Entity("EOM.Web.Models.EvaluationScore", b =>
                {
                    b.HasOne("EOM.Web.Models.Evaluation", "Evaluation")
                        .WithMany("EvaluationScores")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EOM.Web.Models.SubCriteria", "SubCriteria")
                        .WithMany("EvaluationScores")
                        .HasForeignKey("SubCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("SubCriteria");
                });

            modelBuilder.Entity("EOM.Web.Models.ManagerScore", b =>
                {
                    b.HasOne("EOM.Web.Models.Nomination", "Nomination")
                        .WithMany("ManagerScores")
                        .HasForeignKey("NominationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EOM.Web.Models.SubCriteria", "SubCriteria")
                        .WithMany("ManagerScores")
                        .HasForeignKey("SubCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomination");

                    b.Navigation("SubCriteria");
                });

            modelBuilder.Entity("EOM.Web.Models.Nomination", b =>
                {
                    b.HasOne("EOM.Web.Models.AwardCycle", "AwardCycle")
                        .WithMany("Nominations")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EOM.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EOM.Web.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwardCycle");

                    b.Navigation("Employee");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("EOM.Web.Models.SubCriteria", b =>
                {
                    b.HasOne("EOM.Web.Models.Criterion", "Criterion")
                        .WithMany("SubCriteria")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");
                });

            modelBuilder.Entity("EOM.Web.Models.AwardCycle", b =>
                {
                    b.Navigation("Nominations");
                });

            modelBuilder.Entity("EOM.Web.Models.AwardType", b =>
                {
                    b.Navigation("AwardCycles");

                    b.Navigation("Criteria");

                    b.Navigation("DepartmentQuotas");
                });

            modelBuilder.Entity("EOM.Web.Models.CommitteeMember", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("EOM.Web.Models.Criterion", b =>
                {
                    b.Navigation("SubCriteria");
                });

            modelBuilder.Entity("EOM.Web.Models.Employee", b =>
                {
                    b.Navigation("ManagedEmployees");

                    b.Navigation("Managers");
                });

            modelBuilder.Entity("EOM.Web.Models.Evaluation", b =>
                {
                    b.Navigation("EvaluationScores");
                });

            modelBuilder.Entity("EOM.Web.Models.Nomination", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("ManagerScores");
                });

            modelBuilder.Entity("EOM.Web.Models.SubCriteria", b =>
                {
                    b.Navigation("EvaluationScores");

                    b.Navigation("ManagerScores");
                });
#pragma warning restore 612, 618
        }
    }
}
